### ISSUE TITLE
Use a [Featured] tag to control which posts are featured?

### ISSUE THREAD

**Issue by jgostick** [sw-yx/swyxkit#155]
I got this working and am *really* excited and grateful for your efforts. 

I am in the process of customizing my [landing page](https://jgostick.netlify.app/) and I think I need to manualy edit the "FeatureCard.story.svelte" file.  I figured it'd be super helpful I could could just tag a post as "Featured" to make it show up on the home page, so thought I'd make a feature request.

PS- I don't know much about js or svelte otherwise I'd considered making a PR instead of a feature request.

**Comment by sw-yx** [comment]
hey @jgostick ! awesome that you got it working!

so you dont actually need to edit FeatureCard.story.svelte - you just edit these lines

https://github.com/sw-yx/swyxkit/blob/343a5acd34e91861590977f366bb2fe49c5cc37c/src/routes/%2Bpage.svelte#L76-L78

and that should work.

i'm not going to implement the "tag as Featured" thing because that would be overengineering compared to this simple editing process. thanks for asking! 

feel free to ask followup qtns here.
